# Generated by Django 3.0.6 on 2020-05-07 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_actualite_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='actualite',
            name='categorie',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dash.Categorie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerabilite',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dash.Categorie'),
            preserve_default=False,
        ),
    ]
